/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-09-11 01:28:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.sql.*;

public final class NewFile4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/jspworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/dbconn.jsp", Long.valueOf(1599024912774L));
    _jspx_dependants.put("jar:file:/C:/jspworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1599018528896L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fparam_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fparam_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.release();
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.release();
    _005fjspx_005ftagPool_005fsql_005fparam_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  // 데이터베이스 입력 로직
    Connection con=null;
    String driver = "oracle.jdbc.driver.OracleDriver";
    String url = "jdbc:oracle:thin:@localhost:1521:XE";
    
    Class.forName(driver);
    con=DriverManager.getConnection(url,"hr","hr");
 
      out.write('\r');
      out.write('\n');

request.setCharacterEncoding("utf-8");
String facname1 =request.getParameter("sellist1"); 
String cartype1 =request.getParameter("sellist2"); 
String carnum1 =request.getParameter("sellist3"); 


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./resources/css/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<title>중고차 장기 검색</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script>\r\n");
      out.write("function goDate(){\r\n");
      out.write("\tlet form= document.userinput;\r\n");
      out.write("\tform.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function chtest1(){\r\n");
      out.write("\tdocument.getElementById(\"sellist2\").value=null;\r\n");
      out.write("\tdocument.getElementById(\"sellist2\").disabled=false;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function chtest2(){\r\n");
      out.write("\tdocument.getElementById(\"sellist3\").value=null;\r\n");
      out.write("\tdocument.getElementById(\"sellist3\").disabled=false;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write(" <script>\r\n");
      out.write(" function test1(){\r\n");
      out.write("\t \r\n");
      out.write(" let target1=document.getElementById(\"sellist1\");\r\n");
      out.write("\r\n");
      out.write("/*  alert('선택된 옵션 text 값=' + target1.options[target1.selectedIndex].text);     // 옵션 text 값 */\r\n");
      out.write(" alert('선택된 옵션 value 값=' + target1.options[target1.selectedIndex].value);     // 옵션 value 값\r\n");
      out.write("\r\n");
      out.write(" let target2=document.getElementById(\"sellist2\");\r\n");
      out.write("\r\n");
      out.write("/*  alert('선택된 옵션 text 값=' + target2.options[target2.selectedIndex].text);     // 옵션 text 값 */\r\n");
      out.write(" alert('선택된 옵션 value 값=' + target2.options[target2.selectedIndex].value);     // 옵션 value 값\r\n");
      out.write("\r\n");
      out.write(" let target3=document.getElementById(\"sellist3\");\r\n");
      out.write("\r\n");
      out.write("/*  alert('선택된 옵션 text 값=' + target3.options[target3.selectedIndex].text);     // 옵션 text 값 */\r\n");
      out.write(" alert('선택된 옵션 value 값=' + target3.options[target3.selectedIndex].value);     // 옵션 value 값\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("function fchk(){\r\n");
      out.write("\tlet chk_obj = document.getElementsByName(\"example1\");\r\n");
      out.write("\tlet chk_leng = chk_obj.length;\r\n");
      out.write("\tlet checked = 0; \r\n");
      out.write("\r\n");
      out.write("\tfor(i=0;i<chk_leng;i++){\r\n");
      out.write("\t\tif(chk_obj[i].checked==true){\r\n");
      out.write("\t\t\tchecked +=1;\r\n");
      out.write("\t\t\talert(chk_obj[i].value);\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("if(checked==0){\r\n");
      out.write("\talert(\"선택한정보가 없습니다.\");\r\n");
      out.write("\treturn;\r\n");
      out.write("}else{\r\n");
      out.write("\talert(checked+\"개선택\");\r\n");
      out.write("\treturn;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function fchk1(){\r\n");
      out.write("\tlet chk_obj = document.getElementsByName(\"example2\");\r\n");
      out.write("\tlet chk_leng = chk_obj.length;\r\n");
      out.write("\tlet checked = 0; \r\n");
      out.write("\r\n");
      out.write("\tfor(i=0;i<chk_leng;i++){\r\n");
      out.write("\t\tif(chk_obj[i].checked==true){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tchecked +=1;\r\n");
      out.write("\t\t\talert(chk_obj[i].value);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if(checked==0){\r\n");
      out.write("\talert(\"선택한정보가 없습니다.\");\r\n");
      out.write("\treturn;\r\n");
      out.write("}else{\r\n");
      out.write("\talert(checked+\"개선택\");\r\n");
      out.write("\treturn;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("<h2>중고차 장기 렌트</h2>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("   \r\n");
      out.write("  <div class=\"container\" style=\"border:solid 2px;\">\r\n");
      out.write("  \r\n");
      out.write(" <form method=\"post\" action=\"NewFile7.jsp\" name=\"userinput\"  >\r\n");
      out.write("    <div class=\"row\" >\r\n");
      out.write("     <span class=\"col-sm-1\">&nbsp;</span>\r\n");
      out.write("     <div class=\"col-sm-3\">\r\n");
      out.write("     ");
      if (_jspx_meth_sql_005fsetDataSource_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      //  sql:query
      org.apache.taglibs.standard.tag.rt.sql.QueryTag _jspx_th_sql_005fquery_005f0 = (org.apache.taglibs.standard.tag.rt.sql.QueryTag) _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.QueryTag.class);
      boolean _jspx_th_sql_005fquery_005f0_reused = false;
      try {
        _jspx_th_sql_005fquery_005f0.setPageContext(_jspx_page_context);
        _jspx_th_sql_005fquery_005f0.setParent(null);
        // /NewFile4.jsp(151,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sql_005fquery_005f0.setVar("resultSet");
        // /NewFile4.jsp(151,3) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sql_005fquery_005f0.setDataSource((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dataSource}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int[] _jspx_push_body_count_sql_005fquery_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_sql_005fquery_005f0 = _jspx_th_sql_005fquery_005f0.doStartTag();
          if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              _jspx_push_body_count_sql_005fquery_005f0[0]++;
              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fquery_005f0);
            }
            do {
              out.write("\r\n");
              out.write("\t\t\tselect * from member where facname=?\r\n");
              out.write("\t\t\t ");
              //  sql:param
              org.apache.taglibs.standard.tag.rt.sql.ParamTag _jspx_th_sql_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.sql.ParamTag) _005fjspx_005ftagPool_005fsql_005fparam_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.sql.ParamTag.class);
              boolean _jspx_th_sql_005fparam_005f0_reused = false;
              try {
                _jspx_th_sql_005fparam_005f0.setPageContext(_jspx_page_context);
                _jspx_th_sql_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sql_005fquery_005f0);
                // /NewFile4.jsp(153,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sql_005fparam_005f0.setValue(facname1 );
                int _jspx_eval_sql_005fparam_005f0 = _jspx_th_sql_005fparam_005f0.doStartTag();
                if (_jspx_th_sql_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
                _005fjspx_005ftagPool_005fsql_005fparam_0026_005fvalue_005fnobody.reuse(_jspx_th_sql_005fparam_005f0);
                _jspx_th_sql_005fparam_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fparam_005f0_reused);
              }
              out.write("\r\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_sql_005fquery_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
              _jspx_push_body_count_sql_005fquery_005f0[0]--;
            }
          }
          if (_jspx_th_sql_005fquery_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_sql_005fquery_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_sql_005fquery_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_sql_005fquery_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fquery_005f0);
        _jspx_th_sql_005fquery_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fquery_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fquery_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("       <select  class=\"form-control\" id=\"sellist1\" name=\"sellist1\"  autofocus>\r\n");
      out.write("        <option >제조사 선택 </option>\r\n");
      out.write("        <option value=\"기아\" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(">기아 </option>\r\n");
      out.write("        <option value=\"현대\" ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(">현대</option>\r\n");
      out.write("        <option value=\"르노/삼성\" ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(">르노/삼성</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-sm-3\">\r\n");
      out.write("      <select class=\"form-control\" id=\"sellist2\" name=\"sellist2\" onchange=\"chtest2()\" >\r\n");
      out.write("        <option disabled>차량 유형 선택</option>\r\n");
      out.write("        <option value=\"소형\" ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(">소형</option>\r\n");
      out.write("        <option value=\"중형\" ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write(">중형</option>\r\n");
      out.write("        <option value=\"대형\" ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write(">대형</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
      //  sql:query
      org.apache.taglibs.standard.tag.rt.sql.QueryTag _jspx_th_sql_005fquery_005f1 = (org.apache.taglibs.standard.tag.rt.sql.QueryTag) _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.QueryTag.class);
      boolean _jspx_th_sql_005fquery_005f1_reused = false;
      try {
        _jspx_th_sql_005fquery_005f1.setPageContext(_jspx_page_context);
        _jspx_th_sql_005fquery_005f1.setParent(null);
        // /NewFile4.jsp(172,6) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sql_005fquery_005f1.setVar("resultSet");
        // /NewFile4.jsp(172,6) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sql_005fquery_005f1.setDataSource((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dataSource}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int[] _jspx_push_body_count_sql_005fquery_005f1 = new int[] { 0 };
        try {
          int _jspx_eval_sql_005fquery_005f1 = _jspx_th_sql_005fquery_005f1.doStartTag();
          if (_jspx_eval_sql_005fquery_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_sql_005fquery_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              _jspx_push_body_count_sql_005fquery_005f1[0]++;
              out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fquery_005f1);
            }
            do {
              out.write("\r\n");
              out.write("\t\t\tselect * from member where facname=?\r\n");
              out.write("\t\t\t ");
              //  sql:param
              org.apache.taglibs.standard.tag.rt.sql.ParamTag _jspx_th_sql_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.sql.ParamTag) _005fjspx_005ftagPool_005fsql_005fparam_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.sql.ParamTag.class);
              boolean _jspx_th_sql_005fparam_005f1_reused = false;
              try {
                _jspx_th_sql_005fparam_005f1.setPageContext(_jspx_page_context);
                _jspx_th_sql_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sql_005fquery_005f1);
                // /NewFile4.jsp(174,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sql_005fparam_005f1.setValue(facname1 );
                int _jspx_eval_sql_005fparam_005f1 = _jspx_th_sql_005fparam_005f1.doStartTag();
                if (_jspx_th_sql_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
                _005fjspx_005ftagPool_005fsql_005fparam_0026_005fvalue_005fnobody.reuse(_jspx_th_sql_005fparam_005f1);
                _jspx_th_sql_005fparam_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_sql_005fparam_005f1_reused);
              }
              out.write("\r\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_sql_005fquery_005f1.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_sql_005fquery_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
              _jspx_push_body_count_sql_005fquery_005f1[0]--;
            }
          }
          if (_jspx_th_sql_005fquery_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_sql_005fquery_005f1[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_sql_005fquery_005f1.doCatch(_jspx_exception);
        } finally {
          _jspx_th_sql_005fquery_005f1.doFinally();
        }
        _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fquery_005f1);
        _jspx_th_sql_005fquery_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fquery_005f1, _jsp_getInstanceManager(), _jspx_th_sql_005fquery_005f1_reused);
      }
      out.write("\r\n");
      out.write("      <div class=\"col-sm-3\">\r\n");
      out.write("      <select class=\"form-control\" id=\"sellist3\" name=\"sellist3\" disabled>\r\n");
      out.write("        <option disabled>차량 선택</option>\r\n");
      out.write("        <option value=\"2\" ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write(">2</option>\r\n");
      out.write("        <option value=\"3\" ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write(">3</option>\r\n");
      out.write("        <option value=\"4\" ");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write(">4</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write(" <input id=\"tess\" type=\"submit\" class=\"btn btn-primary col-sm-1\" value=\"검색\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  <br><br>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("     <div class=\"row\">\r\n");
      out.write("     <span class=\"col-sm-1\">&nbsp;&nbsp;&nbsp;</span> \r\n");
      out.write("    <span class=\"col-sm-1\"><strong>연료 :</strong></span>\r\n");
      out.write("    <div class=\"col-sm-8\">\r\n");
      out.write("     <span class=\"col-sm-1\">&nbsp;&nbsp;&nbsp;</span> \r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("       <input type=\"checkbox\" value=\"전체\" name=\"example1\"><strong>&nbsp;전체&nbsp;</strong>\r\n");
      out.write("     <!--  <label class=\"custom-control-label\" for=\"customRadio1\"><strong>&nbsp;전체&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"휘발유\"  name=\"example1\"><strong>&nbsp;휘발유&nbsp;</strong>\r\n");
      out.write("      <!-- <label class=\"custom-control-label\" for=\"customRadio2\"><strong>&nbsp;휘발유&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"경유\" name=\"example1\"><strong>&nbsp;경유&nbsp;</strong>\r\n");
      out.write("     <!--  <label class=\"custom-control-label\" for=\"customRadio3\"><strong>&nbsp;경유&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"LPG\" name=\"example1\"><strong>&nbsp;LPG&nbsp;</strong>\r\n");
      out.write("    <!--   <label class=\"custom-control-label\" for=\"customRadio4\"><strong>&nbsp;LPG&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"전기\" name=\"example1\"><strong>&nbsp;전기&nbsp;</strong>\r\n");
      out.write("    <!--   <label class=\"custom-control-label\" for=\"customRadio5\"><strong>&nbsp;전기&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"하이브리드\" name=\"example1\"><strong>&nbsp;하이브리드&nbsp;</strong>\r\n");
      out.write("   <!--    <label class=\"custom-control-label\" for=\"customRadio6\"><strong>&nbsp;하이브리드&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <!--    <input type=\"button\" value=\"확인\" onclick=\"Check(this.form);\"> -->\r\n");
      out.write("    <input type=\"submit\" value=\"검색\" class= \"col-sm-1\">\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <br>\r\n");
      out.write("  \r\n");
      out.write("   <form method=\"post\" onsubmit=\"fchk1();\">\r\n");
      out.write("     <div class=\"row\">\r\n");
      out.write("     <span class=\"col-sm-1\">&nbsp;&nbsp;&nbsp;</span> \r\n");
      out.write("    <span class=\"col-sm-1\"><strong>지점 :</strong></span>\r\n");
      out.write("    <div class=\"col-sm-8\">\r\n");
      out.write("     <span class=\"col-sm-1\">&nbsp;&nbsp;&nbsp;</span> \r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("       <input type=\"checkbox\" value=\"전체\" name=\"example2\"><strong>&nbsp;전체&nbsp;</strong>\r\n");
      out.write("     <!--  <label class=\"custom-control-label\" for=\"customRadio7\"><strong>&nbsp;전체&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"서울\" name=\"example2\"><strong>&nbsp;서울&nbsp;</strong>\r\n");
      out.write("      <!-- <label class=\"custom-control-label\" for=\"customRadio8\"><strong>&nbsp;서울&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"경기\" name=\"example2\"><strong>&nbsp;경기&nbsp;</strong>\r\n");
      out.write("<!--       <label class=\"custom-control-label\" for=\"customRadio9\"><strong>&nbsp;경기&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"충청\" name=\"example2\"><strong>&nbsp;충청&nbsp;</strong>\r\n");
      out.write("     <!--  <label class=\"custom-control-label\" for=\"customRadio10\"><strong>&nbsp;충청&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"강원\" name=\"example2\"><strong>&nbsp;강원&nbsp;</strong>\r\n");
      out.write(" <!--      <label class=\"custom-control-label\" for=\"customRadio11\"><strong>&nbsp;강원&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-check-inline\">\r\n");
      out.write("      <input type=\"checkbox\" value=\"경상\" name=\"example2\"><strong>&nbsp;경상&nbsp;</strong>\r\n");
      out.write("   <!--    <label class=\"custom-control-label\" for=\"customRadio12\"><strong>&nbsp;경상&nbsp;</strong></label> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <input type=\"submit\" value=\"검색\" class=\"col-sm-1\">\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<br>\r\n");
      out.write("<h3>검색결과</h3>\r\n");
      out.write("<hr style=\"border: solid 1px black \" /> \r\n");
      out.write("\r\n");
ResultSet rs=null;
PreparedStatement pstmt=null;
try{
	String sql1="select * from member where facname=? and cartype=? and carnum=?";
	pstmt = con.prepareStatement(sql1); 
 	pstmt.setString(1, facname1);
 	pstmt.setString(2, cartype1);
 	pstmt.setString(3, carnum1);
	rs=pstmt.executeQuery();
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row\" >\r\n");
      out.write("\t\r\n");
      out.write("\t");
 while(rs.next()){
		String id=rs.getString("id");
		String carname=rs.getString("carname");
		String facname=rs.getString("facname");
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div  onclick=\"location.href='lent_long_old.jsp?carname=");
      out.print(URLEncoder.encode(carname,"utf-8") );
      out.write("'\" class=\"card col-sm-6 \" style=\"width:500px; height:300px; \">\r\n");
      out.write("    <div >\r\n");
      out.write("   <img class=\"card-img-top col-sm-8\" src=\"./resources/images/car.jpg\" alt=\"Card image\" style=\"width:250px\">\r\n");
      out.write("    <span class=\"col-sm-3\"><strong>");
      out.print(carname);
      out.write(" </strong></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("      <a class=\"card-title\" style=\"border:1px solid\">소비자가 </a>\r\n");
      out.write("      <a >14,860,000원</a>\r\n");
      out.write("      <a class=\"card-title\" style=\"border:1px solid red\"><span style=\"color:red\"><strong>월 렌탈료</strong></span></a>\r\n");
      out.write("      <a >&nbsp;&nbsp; <span style=\"color:red\"><strong>346,000원~</strong></span></a>\r\n");
      out.write("     \r\n");
      out.write("      <hr style=\"border:1px solid\"></hr>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("      <ul class=\"col-sm-6\">\r\n");
      out.write("      \r\n");
      out.write("      <li>차량 등록 <span>");
      out.print(id );
      out.write("</span></li>\r\n");
      out.write("      <li>주행거리 <span>");
      out.print(facname );
      out.write("</span></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"col-sm-6\">\r\n");
      out.write("      <li>계약기간 <span>최대21개월</span></li>\r\n");
      out.write("      <li>지역  <span>부산</span></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  ");
 
	}
}catch(Exception e){
	e.getStackTrace();
}finally{
	
		if(rs != null)
		rs.close();
		if(pstmt != null)
			pstmt.close();
		if(con != null)
			con.close();
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sql_005fsetDataSource_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:setDataSource
    org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag _jspx_th_sql_005fsetDataSource_005f0 = (org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag) _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.get(org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag.class);
    boolean _jspx_th_sql_005fsetDataSource_005f0_reused = false;
    try {
      _jspx_th_sql_005fsetDataSource_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fsetDataSource_005f0.setParent(null);
      // /NewFile4.jsp(146,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setVar("dataSource");
      // /NewFile4.jsp(146,5) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUrl("jdbc:oracle:thin:@localhost:1521:XE");
      // /NewFile4.jsp(146,5) name = driver type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setDriver("oracle.jdbc.driver.OracleDriver");
      // /NewFile4.jsp(146,5) name = user type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUser("hr");
      // /NewFile4.jsp(146,5) name = password type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setPassword("hr");
      int _jspx_eval_sql_005fsetDataSource_005f0 = _jspx_th_sql_005fsetDataSource_005f0.doStartTag();
      if (_jspx_th_sql_005fsetDataSource_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.reuse(_jspx_th_sql_005fsetDataSource_005f0);
      _jspx_th_sql_005fsetDataSource_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fsetDataSource_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fsetDataSource_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /NewFile4.jsp(158,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist1=='기아'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /NewFile4.jsp(159,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist1 =='현대'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /NewFile4.jsp(160,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist1 =='르노/삼성'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /NewFile4.jsp(167,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist2 =='소형'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /NewFile4.jsp(168,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist2 =='중형'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /NewFile4.jsp(169,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist2 =='대형'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /NewFile4.jsp(179,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist3 =='2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /NewFile4.jsp(180,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist3 =='3'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /NewFile4.jsp(181,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sellist3 =='4'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }
}
