/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-09-23 03:41:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rent_005flong_005fnew_005fcar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<style>\r\n");
      out.write(".accordion {\r\n");
      out.write("\tbackground-color: #eee;\r\n");
      out.write("\tcolor: #444;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 18px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\ttransition: 0.4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".active, .accordion:hover {\r\n");
      out.write("\tbackground-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accordion:after {\r\n");
      out.write("\tcontent: '\\002B';\r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".active:after {\r\n");
      out.write("\tcontent: \"\\2212\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel {\r\n");
      out.write("\tpadding: 0 18px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tmax-height: 0;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttransition: max-height 0.2s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.fixed {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\t/*   text-align: center; */\r\n");
      out.write("\twidth: 65%;\r\n");
      out.write("\t/* margin-right: 150px;\r\n");
      out.write("  margin-left: 150px; */\r\n");
      out.write("\t/*  border: 3px solid black; */\r\n");
      out.write("\tbackground-color: orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.f {\r\n");
      out.write("\tborder: 1px solid #eeeeee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accordion {\r\n");
      out.write("\tbackground-color: #eee;\r\n");
      out.write("\tcolor: #444;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 18px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\ttransition: 0.4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dt {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dd {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>TT 신차 장기 렌터카 목록</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container col-sm-10\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"display-5\">TT 신차 장기 렌터카 목록</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--  -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<table style=\"width: 100%\" >\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\"><h2>TT 신차 장기 렌터카 목록</h2></td>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">? > 장기렌터카 > TT 신차 장기 렌터카 > TT 신차 장기 렌터카 목록</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <br> <br>\r\n");
      out.write("\r\n");
      out.write("   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.model}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.segment }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.fuel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.trim }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.manufacturer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.year }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<table style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><h3>견적 조회</h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\" ><button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-lg\" onclick=\"location.href='rent_long_new_car.jsp' \">목록</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"border: 1px solid #eeeeee;\">\r\n");
      out.write("\t\t\t\t<table class=\"table\" style=\"height: 200px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"6\" style=\"width: 35%\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://image.speedmate.com/speedimg/rentcar/687048/20200515/17/175355397mbl_41f63b7b95834433a740529d4de12a75.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"현대자동차 G80 2.5T AWD\" width=\"100%\" height=\"80%\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"50%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.manufacturer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.trim }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("GLC-CLASS</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr height=\"50%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">프리미엄 준중형 SUV의 정석, 메르세데스 벤츠 GLC 250</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <br> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<table style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><h4>상세 차량 및 옵션 선택</h4></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\">선구매 차량은 차종,내/외부 색상,옵션 선택이 불가할 수 있습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table talbe-hover\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>상세 차량<a data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"차량의 상세 모델/트림입니다.\"><img alt=\"물음표\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"20px\"></a></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carInfo.model}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>82,900,000원</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>외부 색상<a data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"차량 외부(보닛, 도어, 트렁크 등)의 색상입니다.\"><img alt=\"물음표\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"20px\"></a></td>\r\n");
      out.write("\t\t\t\t\t<td>(197)obsidian black</td>\r\n");
      out.write("\t\t\t\t\t<td>0원</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>내부 색상<a data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"차량 내부(시트/마감재 등)의 색상입니다.\"><img alt=\"물음표\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"20px\"></a></td>\r\n");
      out.write("\t\t\t\t\t<td>(651)DINAMICA/ARTICO man-made</td>\r\n");
      out.write("\t\t\t\t\t<td>0원</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>차량 옵션<a data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"차량에 추가할 수 있는 편의/안전사양 등 입니다.(제조사 제공)\"><img alt=\"물음표\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"20px\"></a></td>\r\n");
      out.write("\t\t\t\t\t<td>(옵션없음)</td>\r\n");
      out.write("\t\t\t\t\t<td>0원</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h4>렌트 조건 선택</h4>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"accordion\">\r\n");
      out.write("\t\t\t\t계약 기간 <span id=\"result1\"><a data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\tdata-placement=\"bottom\" title=\"차량 대여 기간입니다.\"><img alt=\"물음표\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\theight=\"20px\"></a></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<span>차량 운행할수 있는 총 대여기간: </span> <select name=\"cntrTermMm\"\r\n");
      out.write("\t\t\t\t\tid=\"cntrTermMm1\" class=\"option01\" onchange=\"checkTest1()\">\r\n");
      out.write("\t\t\t\t\t<option value=\"36 개월\">36 개월</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"48 개월\">48 개월</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"60 개월\">60 개월</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"accordion\">\r\n");
      out.write("\t\t\t\t약정 주행거리 <span id=\"result2\"><a data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\tdata-placement=\"bottom\"\r\n");
      out.write("\t\t\t\t\ttitle=\"계약기간 총 주행거리 초과 시 위약금발생(총 주행거리 = 계약기간 x 약정 주행거리)* 위약금은 하단 안내 참조\"><img\r\n");
      out.write("\t\t\t\t\t\talt=\"물음표\" src=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\theight=\"20px\"></a></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<span>계약 기간 총 주행거리 초과 시 위약금 발생 </span> <input id=\"a\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"2만 Km 이하\" onclick=\"msg1()\"> <input id=\"b\"\r\n");
      out.write("\t\t\t\t\ttype=\"button\" value=\"3만 Km 이하\" onclick=\"msg2()\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"accordion\">\r\n");
      out.write("\t\t\t\t운전자 범위<span id=\"result3\"><a data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\tdata-placement=\"bottom\" title=\"차량 운전을 누가하는지 운전 대상자의 범위입니다.\"><img\r\n");
      out.write("\t\t\t\t\t\talt=\"물음표\" src=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\theight=\"20px\"></a></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<span>계약자의 직계 가족만 운전가능 </span> <input id=\"a1\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"가족 한정\" onclick=\"msg4()\"> <input id=\"b1\"\r\n");
      out.write("\t\t\t\t\ttype=\"button\" value=\"1인 지정\" onclick=\"msg5()\"> <input\r\n");
      out.write("\t\t\t\t\tid=\"c1\" type=\"button\" value=\"누구나\" onclick=\"msg6()\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"accordion\">\r\n");
      out.write("\t\t\t\t사고 시 차량 대여 <span id=\"result4\"><a data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\tdata-placement=\"bottom\"\r\n");
      out.write("\t\t\t\t\ttitle=\"사고로 차량 수리 시 수리기간동안 다른 차량을 대여하실 수 있는 서비스입니다.\"><img\r\n");
      out.write("\t\t\t\t\t\talt=\"물음표\" src=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\theight=\"20px\"></a></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<span>사고 발생시 대차 서비스 미제공 </span> <input id=\"a2\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"포함\" onclick=\"msg7()\"> <input id=\"b2\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"불포함\" onclick=\"msg8()\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"accordion\">\r\n");
      out.write("\t\t\t\t정비 서비스 <span id=\"result5\"><a data-toggle=\"tooltip\"\r\n");
      out.write("\t\t\t\t\tdata-placement=\"bottom\"\r\n");
      out.write("\t\t\t\t\ttitle=\"차량 대여기간 동안 정기적으로 차량 정비를 받을 수 있는 서비스입니다.\"><img alt=\"물음표\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./resources/images/question mark.png\" width=\"20px\"\r\n");
      out.write("\t\t\t\t\t\theight=\"20px\"></a></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<span>대여기간 동안 정비 서비스 이용 </span> <input id=\"a3\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"미포함\" onclick=\"msg9()\"> <input id=\"b3\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"기본 정비 상품\" onclick=\"msg10()\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table class=\"table talbe-hover\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>차계약 종료 후 차량 소유</td>\r\n");
      out.write("\t\t\t\t\t<td>계약 종료 시 차량 소유/반납 여부를 선택하실 수 있습니다.</td>\r\n");
      out.write("\t\t\t\t\t<td>(차량 인수가: 32,331,000원)</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"f\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><span class=\"cl-point2\">계약 종료 후 차량의 소유/반납 여부를 선택하실\r\n");
      out.write("\t\t\t\t\t\t\t수 있습니다</span></li>\r\n");
      out.write("\t\t\t\t\t<li>월 렌탈료는 신용심사 결과, 담보조건, 담보율에 따라 변경될 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t<li>차량 이미지는 고객님의 이해를 돕기 위한 이미지로 실제 차량과 다를 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t<li>현재 재고 기준의 견적으로 바로 구매하시지 않는 경우 재고 소진으로 구매가 불가할 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t<li>견적을 저장하시면 <span class=\"cl-point2\">MY렌터카 &gt; 장기CAR\r\n");
      out.write("\t\t\t\t\t\t\t&gt; 견적정보</span>에서 견적비교를 하실 수 있습니다.\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>차량 옵션은 제조사의 사정에 따라 변경될 수 있으며, 변경시 별도 연락을 드리겠습니다.</li>\r\n");
      out.write("\t\t\t\t\t<li>SK렌터카 서비스 중 '용품' 혜택은 다이렉트 전용 제공 상품입니다.</li>\r\n");
      out.write("\t\t\t\t\t<li>약정 주행거리 초과 위약금: 1600CC미만(60원/km) , 2000CC미만(80원/km) ,\r\n");
      out.write("\t\t\t\t\t\t2000CC이상(100원/km) , 수입차(200원/km) , 테슬라(450원/km)</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('[data-toggle=\"tooltip\"]').tooltip();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction checkTest1() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"cntrTermMm1\").value;\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById(\"result1\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction msg1() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"a\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result2\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction msg2() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"b\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result2\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction msg4() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"a1\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result3\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction msg5() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"b1\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result3\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction msg6() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"c1\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result3\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction msg7() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"a2\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result4\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction msg8() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"b2\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result4\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction msg9() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"a3\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result5\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction msg10() {\r\n");
      out.write("\t\t\tlet testValue = document.getElementById(\"b3\").value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"result5\").innerHTML = testValue;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar acc = document.getElementsByClassName(\"accordion\");\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i = 0; i < acc.length; i++) {\r\n");
      out.write("\t\t\tacc[i].addEventListener(\"click\", function() {\r\n");
      out.write("\t\t\t\tthis.classList.toggle(\"active\");\r\n");
      out.write("\t\t\t\tvar panel = this.nextElementSibling;\r\n");
      out.write("\t\t\t\tif (panel.style.maxHeight) {\r\n");
      out.write("\t\t\t\t\tpanel.style.maxHeight = null;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tpanel.style.maxHeight = panel.scrollHeight + \"px\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
