/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-09-18 06:46:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.long_005flent_005foldcar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shortTerm_005fnavbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function discount_window(){\r\n");
      out.write(" \tvar discount_window1 = window.open(\"../payment/shortTerm_payment1.jsp\",\"\", \"left=500, top=100, width=900, height=500,toolbar=no, scrollbars=no, status=no, resizable=no\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container col-sm-6 fixed-bottom\" style=\"border:1px solid orange;\">\r\n");
      out.write("    <div class=\"row card\" style=\"background-color: orange;\">\r\n");
      out.write("        <!-- <a class=\"card-link\" data-toggle=\"collapse\" href=\"#collapsebar\"> -->\r\n");
      out.write("       \t\t   <nav class=\"container navbar navbar-expand-sm navbar-dark bottom\" style=\"height: 70px;\">\r\n");
      out.write("  \t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-8\" style=\"color: white;\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<h4 class=\"col\">총 결제금액</h4><h4 class=\"float-right\">0원</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t  \t\t <div class=\"col-sm-2\"></div>\r\n");
      out.write("\t\t  \t\t &nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"row btn col-sm-5 border\" id=\"reset\" style=\"color: white;font-size: 15px;\">초기화</button>\r\n");
      out.write("\t\t\t\t &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn col-sm-5 border float-right\" id=\"calc\" style=\"color: white; font-size: 15px;\"onclick=\"location.href='../payment/shortTerm_payment2.jsp'\" >예약하기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        <div class=\"card-body\" id=\"more_open\" style=\"background-color: white;\">\r\n");
      out.write("           <!-- <div class=\"container col-sm-6\"> -->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<table style=\"width: 90%;\">\r\n");
      out.write("\t\t\t\t<tr class=\"row\" style=\"border-bottom: 1px solid black;\"><td class=\"container\"><h5>대여현황</h5></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>대여일시<span class=\"float-right\">2020-09-16 11:42</span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>반납일시<span class=\"float-right\">2020-09-16 11:42</span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>대여지점<span class=\"float-right\">제주지점</span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>반납지점<span class=\"float-right\">제주지점</span></b></td></tr>\t\t\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>대여차량<span class=\"float-right\">스포티지</span></b></td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<table style=\"width: 90%;\">\r\n");
      out.write("\t\t\t\t<tr class=\"row\" style=\"border-bottom: 1px solid black;\"><td class=\"container\"><h5>계약자 정보</h5></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>이름<span class=\"float-right\">홍길동</span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>휴대폰<span class=\"float-right\">0101234567</span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>생년월일<span class=\"float-right\">19990101</span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>이메일<span class=\"float-right\">hong@naver.com</span></b></td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<table style=\"width: 90%;\">\r\n");
      out.write("\t\t\t\t<tr class=\"row\" style=\"border-bottom: 1px solid black;\"><td class=\"col-sm-12\"><h5>예약금액<button class=\"row btn btn-sm border float-right\" onclick=\"discount_window()\">할인적용</button></h5></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>표준요금<span class=\"float-right\">54000<span>원</span></span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>편도수수료<span class=\"float-right\">2000<span>원</span></span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>차량손해면책제도<span class=\"float-right\">0<span>원</span></span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>총 할인금액<span class=\"float-right\">52000<span>원</span></span></b></td></tr>\r\n");
      out.write("\t\t\t\t<tr class=\"row border-bottom\"style=\"height: 50px;\"><td class=\"col-sm-12\"><b>이벤트추가할인<span class=\"float-right\">0<span>원</span></span></b></td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<p class=\"row\">* 차량손해면책제도는 할인 적용 제외</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
